In [1]:
import numpy as np

In [2]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

### 【問題1】行列積を手計算する

AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

- 数式
$$
c_{i,j}=\sum^{2}_{k=0}a_{i,k}b_{k,j}
$$

$$
A =
\begin{bmatrix}
-1 & 2 & 3 \\ 4 & -5 & 6 \\ 7 & 8 & -9
\end{bmatrix} \quad
,B =
\begin{bmatrix}
0 & 2 & 1 \\ 0 & 2 & -8 \\ 2 & 9 & -1
\end{bmatrix}
$$

- AとBの行列積の式\
\begin{eqnarray}
6, 29, -20 &=& -1*0+2*0+3*2, -1*2+2*2+3*9, -1*1+2*-8+3*-1\\
12, 52, 38 &=& 4*0+-5*0+6*2, 4*2+-5*2+6*9, 4*1+-5*-8+6*-1\\
-18, -51, -48 &=& 7*0+8*0+-9*2, 7*2+8*2+-9*9, 7*1+8*-8+-9*-1
\end{eqnarray}

- AとBの行列積の結果\
\begin{bmatrix}
6 & 29 & -20 \\ 12 & 52 & 38 \\ -18 & -51 & -48
\end{bmatrix}

### 【問題2】NumPyの関数による計算

この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。


これらを使い行列積を計算してください。

《3種類の違い》


np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。


今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。


If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

- np.matmul()

In [3]:
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

- np.dot()

In [4]:
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

- @演算子

In [5]:
a_ndarray@b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

### 【問題3】ある要素の計算を実装

手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。


- 1. 行列Aの(0,0)の要素 $a_{0, 0}$ と行列Bの(0,0)の要素 $b_{0, 0}$ を掛け合わせる
- 2. 行列Aの(0,1)の要素 $a_{0, 1}$ と行列Bの(1,0)の要素 $b_{1, 0}$ を掛け合わせる
- 3. 行列Aの(0,2)の要素 $a_{0, 2}$ と行列Bの(2,0)の要素 $b_{2, 0}$ を掛け合わせる
- 4. それらの値を全て足し合わせる

この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [6]:
r_ndarray = [a_ndarray[0][0]*b_ndarray[0][0]+a_ndarray[0][1]*b_ndarray[1][0]+a_ndarray[0][2]*b_ndarray[2][0]]

In [7]:
r_ndarray

[6]

### 【問題4】行列積を行う関数の作成

問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。


行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。


計算結果である $3 \times 3$ の行列Cの各要素 $c_{i, j}$ は数式で表すと次のようになります。

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。\
インデックス $i$ や $j$ を1増やすと、次の行や列に移ることができます。



- 手計算 

In [8]:
def compute_matrix_product(a_array, b_array):
    """
    行列AとBを引数に受け取り、行列積を返す関数。

    Parameters
    --------------
    a_array: ndarray
    b_array: ndarray

    Returns
    --------------
    c_ndarray: list
    """
    c_ndarray = [[a_array[0][0]*b_array[0][0]+a_array[0][1]*b_array[1][0]+a_array[0][2]*b_array[2][0],
                  a_array[0][0]*b_array[0][1]+a_array[0][1]*b_array[1][1]+a_array[0][2]*b_array[2][1],
                  a_array[0][0]*b_array[0][2]+a_array[0][1]*b_array[1][2]+a_array[0][2]*b_array[2][2]],
                 [a_array[1][0]*b_array[0][0]+a_array[1][1]*b_array[1][0]+a_array[1][2]*b_array[2][0],
                  a_array[1][0]*b_array[0][1]+a_array[1][1]*b_array[1][1]+a_array[1][2]*b_array[2][1],
                  a_array[1][0]*b_array[0][2]+a_array[1][1]*b_array[1][2]+a_array[1][2]*b_array[2][2]],
                 [a_array[2][0]*b_array[0][0]+a_array[2][1]*b_array[1][0]+a_array[2][2]*b_array[2][0],
                  a_array[2][0]*b_array[0][1]+a_array[2][1]*b_array[1][1]+a_array[2][2]*b_array[2][1],
                  a_array[2][0]*b_array[0][2]+a_array[2][1]*b_array[1][2]+a_array[2][2]*b_array[2][2]]]    
    return c_ndarray

In [9]:
c_ndarray = compute_matrix_product(a_ndarray, b_ndarray)
np.array(c_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

- for文(参考)

In [10]:
def compute_matrix_product_for_loop(a_array, b_array):
    """
    行列AとBを引数に受け取り、行列積を返す関数。

    Parameters
    --------------
    a_array: ndarray
    b_array: ndarray

    Returns
    --------------
    c_ndarray_ref: ndarray
    """
    c_ndarray_ref = np.zeros((a_array.shape[0], b_array.shape[1])).astype('int64')
    for i in range(a_array.shape[0]):
        for j in range(b_array.shape[1]):
            element = 0
            for k in range(a_array.shape[1]):
                element += a_array[i][k]*b_array[k][j]
            c_ndarray_ref[i][j] = element
    return c_ndarray_ref

In [11]:
c_ndarray_ref = compute_matrix_product_for_loop(a_ndarray, b_ndarray)
c_ndarray_ref

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

### 【問題5】計算が定義されない入力を判定する

問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。\
この場合、不適切な計算が行われることになります。\
また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。


if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [12]:
def compute_matrix_product_with_detect(d_array, e_array):
    """
    行列DとEを引数に受け取り、行列積が定義されない入力を判定した上で、行列積を返す関数。

    Parameters
    --------------
    d_array: ndarray
    e_array: ndarray

    Returns
    --------------
    c_ndarray_q5: ndarray
    Nothing: D行列の列数とE行列の行数が不一致の場合
    """
    if d_array.shape[1] == e_array.shape[0]:
        c_ndarray_q5 = np.zeros((d_array.shape[0], e_array.shape[1])).astype('int64')
        for i in range(d_array.shape[0]):
            for j in range(e_array.shape[1]):
                element = 0
                for k in range(d_array.shape[1]):
                    element += d_array[i][k]*e_array[k][j]
                c_ndarray_q5[i][j] = element
    else:
        print("D行列の列数とE行列の行数が不一致です。")
        return
    return c_ndarray_q5

In [13]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [14]:
c_ndarray_q5 = compute_matrix_product_with_detect(d_ndarray, e_ndarray)
c_ndarray_q5

D行列の列数とE行列の行数が不一致です。


### 【問題6】転置

片方の行列を転置することで、行列積が計算できるようになります。


np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

- np.transpose()

In [15]:
c_ndarray_q5 = compute_matrix_product_with_detect(d_ndarray, np.transpose(e_ndarray))
c_ndarray_q5

array([[ 46,  -4],
       [-34,  73]])

In [16]:
c_ndarray_q5 = compute_matrix_product_with_detect(np.transpose(d_ndarray), e_ndarray)
c_ndarray_q5

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])

- .Tアトリビュート

In [17]:
c_ndarray_q5 = compute_matrix_product_with_detect(d_ndarray, e_ndarray.T)
c_ndarray_q5

array([[ 46,  -4],
       [-34,  73]])

In [18]:
c_ndarray_q5 = compute_matrix_product_with_detect(d_ndarray.T, e_ndarray)
c_ndarray_q5

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])