### 【問題1】これまで利用してきたクラスの列挙
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。


Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。


<u>メソッド</u>\
インスタンス化を行った後には、`scaler.fit(X)`のような __メソッド__ の実行ができます。`StandardScaler`の`fit`メソッドは後でスケーリングに使われる平均と標準偏差を計算する機能があります。


<u>インスタンス変数（アトリビュート）</u>\
`fit`メソッドにより平均と標準偏差が計算されましたが、見た目には変化があるわけではありません。しかし、scalerインスタンスの内部では計算結果が保存されています。こういったインスタンスの中で値を保存するものを __インスタンス変数__ や __アトリビュート（属性）__ と呼びます。ここで平均が`scaler.mean_`、標準偏差の2乗した値である分散が`scaler.var_`に保存されています。


以下のようにprint文で出力させることができます。


print(`"平均 : {}"`.format(scaler.mean_)) # 平均 : [4.86 3.31 1.45 0.22]\
print(`"分散 : {}"`.format(scaler.var_)) # 分散 : [0.0764 0.0849 0.0105 0.0056]

__《メソッドとインスタンス変数の命名法》__


メソッドやインスタンス変数の命名は関数と同様に、全て小文字で行います。単語をつなぐときにはアンダースコアを入れます。


[はじめに — pep8-ja 1.0 ドキュメント メソッド名とインスタンス変数](https://pep8-ja.readthedocs.io/ja/latest/#id37)

- __これまでの課題で利用してきたコードの中でどのようなクラスがあったか__
 1. Pandas DataFrame
 2. matplotlib ListedColormap
 3. scikit-learn KNeighborsClassifier

### 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。


最低でもそれぞれ5つ以上答えてください。


__《ndarrayやstrもインスタンス》__


ドットをつけるというと、NumPyのndarrayに対して`ndarray.shape`や`ndarray.sum()`のような使い方は何度も利用してきたかと思います。これは、ndarrayもインスタンスオブジェクトであり、`shape`はインスタンス変数、`sum`はメソッドだったということです。


Pythonのコードに登場するデータはどれもインスタンスオブジェクトであり、listやstrもメソッドを持ちます。


（例）


[5. データ構造 — Python 3.7.4 ドキュメント 5.1. リスト型についてもう少し](https://docs.python.org/ja/3/tutorial/datastructures.html#more-on-lists)


l = [`'a'`]\
l.append(`'b'`) # listのappendメソッド

[4. 組み込み型 — Python 3.7.4 ドキュメント 文字列メソッド](https://docs.python.org/ja/3/library/stdtypes.html#string-methods)


s = `'Hello, World!'`\
s.find(`'W'`) # strのfindメソッド

インスタンス変数をメソッドが利用
最終的に以下のようにして標準化を行います。


`X_std = scaler.transform(X)`


これは`fit`メソッドで計算したことでインスタンス変数`mean_`や`var_`に保存されていた値を使い、Xを変換したということです。


このようにクラスには複数のメソッドやインスタンス変数が存在し、これらを組み合わせていろいろな機能を実現します。

- __これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったか__\
    《メソッド》
 1. .mean()
 2. .sum()
 3. .count()
 4. .sort()
 5. .find()\
    《インスタンス変数》
 1. dtype
 2. size
 3. T
 4. ndim
 5. shape

### 【問題3】標準化クラスをスクラッチで作成
理解をより深めるため、`StandardScaler`をスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的には`fit`メソッドと`transform`メソッドを作ります。


今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。


インスタンス変数を作成する際は`self.mean_`のように`self`を付けます。クラスの外から`scaler.mean_`と書いていたscalerの部分が自分自身を表すselfになっています。

In [1]:
import numpy as np
from sklearn.datasets import load_iris

In [2]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = X.mean(axis=0)
        self.var_ = X.var(axis=0) #np.var(X, axis=0)
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_) / np.sqrt(self.var_)
        return X_scaled

In [3]:
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


### 【問題4】 四則演算を行うクラスの作成
上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。


コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。


クラス名や説明文も適切に書き換えてください。

In [4]:
def error_message(err):
    print("エラーが発生しました。")
    print(type(err), err)

In [5]:
class FourArithmeticalOperations():
    """
    加減乗除を行うクラス

    Parameters
    ----------
    value : float
        初期値

    Attributes
    ----------
    value : float
        計算結果
    """        
    def __init__(self, value):
        try:
            #raise Exception
            self.value = float(value)
            print("初期値{}が設定されました".format(self.value))
        except Exception as error:
            error_message(error)

    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        try:
            self.value += float(value2)
        except Exception as error:
            error_message(error)

    def subtract(self, value3):
        """
        受け取った引数をself.valueから引く
        """
        try:
            self.value -= float(value3)
        except Exception as error:
            error_message(error)

    def multiply(self, value4):
        """
        受け取った引数をself.valueに掛ける
        """
        try:
            self.value *= float(value4)
        except Exception as error:
            error_message(error)

    def divide(self, value5):
        """
        受け取った引数をself.valueに除する
        """
        try:
            self.value /= float(value5)
        except Exception as error:
            error_message(error)

In [6]:
example = FourArithmeticalOperations(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.subtract(3)
print("value : {}".format(example.value))
example.multiply(3)
print("value : {}".format(example.value))
example.divide(3)
print("value : {}".format(example.value))

初期値5.0が設定されました
value : 5.0
value : 8.0
value : 5.0
value : 15.0
value : 5.0
